apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: config
  # behavior: replace
  files:
  - application.properties
  
resources:
- deployment.yaml
- service.yaml